lung3: 'data/Lung3.metadata.csv'
gene: 'data/GSE58661_series_matrix.txt.gz'
mem_time_profiling: 'analysis/mem_time_profiling.csv'
dask_roc_file_path: 'analysis/roc_cuve_dask.png'
pandas_roc_file_path: 'analysis/roc_cuve_pandas.png'
log_file_dask : "logs/workflow_dask.log"
log_file_pandas : "logs/workflow_pandas.log"