name: dask_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - notebook
  - pandas
  - seaborn
  - memory_profiler
  - toolz
  - dask
  - pip:
      - dask[complete]==2025.3.0
      - dask-ml==2025.1.0
      - numpy==1.26.4
      - xgboost==3.0.0